### ISSUE TITLE
Menu width on desktop

### ISSUE THREAD

**Issue by SimonCDalzell** [mariospr/compact-quick-settings-gnome-shell-extension#3]
On desktop where there is no battery indicator, the menu ends up a bit narrow. Is there an easy way to force it to a minimum width?

![image](https://user-images.githubusercontent.com/19229302/208093871-1719f9fc-344c-44f4-82d7-4001b3faaa23.png)

**Comment by mariospr** [comment]
Thanks for taking the time to write the report. I checked this by forcing the battery icon not to be added and I see what you mean, but still I think this is a bit subjective (to me is not that awkward) and fixing it at the level of the extension would require, I think, diverging a tad too much from the original Shell's code to make sure the natural width of the menu was a bit bigger, which I'd rather avoid if possible.

Not sure if there's another easier way to fix this, in which case I'm all ears. Closing for now, sorry I can't be more helpful here right now...
