### ISSUE TITLE
Support Fedora 38 and GNOME 44

### ISSUE THREAD

**Issue by dmvolod** [mariospr/compact-quick-settings-gnome-shell-extension#5]
Could you please to update extension Fedora 38 and GNOME 44 which is outdated after update
Also I can confirm, that extension conflicting with Caffeine described in #4 but alternative Espresso extension can be used instead.

**Comment by mariospr** [comment]
I'm still at GNOME 43. I will update it once I upgrade. Thanks for the report.

**Comment by mariospr** [comment]
I've just upgraded the extension to support GNOME 44 and I'm using it now without problems, so I've just submitted it to https://extensions.gnome.org/extension/5527/compact-quick-settings/ up for review. Once it's approved, it should show up in the combo box "Shell version...".

**Comment by mariospr** [comment]
The updated extension is now live, closing
