### ISSUE TITLE
Gnome 46

### ISSUE THREAD

**Issue by rusberiaosa** [mariospr/compact-quick-settings-gnome-shell-extension#6]
gnome version 46 is officially out. Can this extension be updated to support it ?

**Comment by mariospr** [comment]
Yep, will be updated as soon as I get a chance to test it in GNOME 46 (i.e. when I upgrade to Fedora 40)

**Comment by mariospr** [comment]
@ghost The extension has been updated now, you can download it from https://extensions.gnome.org/extension/5527/compact-quick-settings/
